/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.pocetna;

import forme.kurs.FPretragaKursevaTabela;
import forme.kurs.FUnosKursa;
import forme.polaznik.FNoviPolaznik;
import forme.polaznik.FPretragaPolaznika;
import forme.zaposleni.FNoviZaposleni;
import forme.zaposleni.FPretragaZaposlenih;


/**
 *
 * @author Dasa
 */
public class FPocetna extends javax.swing.JFrame {

    /**
     * Creates new form FPocetna
     */
    public FPocetna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbOsnovniMeni = new javax.swing.JMenuBar();
        jmPocetak = new javax.swing.JMenu();
        jmiUnosKursa = new javax.swing.JMenuItem();
        jmiPretragaKursevaTabela = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiKraj = new javax.swing.JMenuItem();
        jmPolaznik = new javax.swing.JMenu();
        jmiNoviPolaznik = new javax.swing.JMenuItem();
        jmiPretragaPolaznika = new javax.swing.JMenuItem();
        jmZaposleni = new javax.swing.JMenu();
        jmiNoviZaposleni = new javax.swing.JMenuItem();
        jmiPretragaZaposlenih = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Skola stranih jezika");
        setAlwaysOnTop(true);

        jmPocetak.setText("Kurs");

        jmiUnosKursa.setText("Novi kurs");
        jmiUnosKursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKursaActionPerformed(evt);
            }
        });
        jmPocetak.add(jmiUnosKursa);

        jmiPretragaKursevaTabela.setText("Pretraga kurseva");
        jmiPretragaKursevaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaKursevaTabelaActionPerformed(evt);
            }
        });
        jmPocetak.add(jmiPretragaKursevaTabela);
        jmPocetak.add(jSeparator1);

        jmiKraj.setText("Kraj");
        jmiKraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKrajActionPerformed(evt);
            }
        });
        jmPocetak.add(jmiKraj);

        jmbOsnovniMeni.add(jmPocetak);

        jmPolaznik.setText(" Polaznik");

        jmiNoviPolaznik.setText("Novi polaznik");
        jmiNoviPolaznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNoviPolaznikActionPerformed(evt);
            }
        });
        jmPolaznik.add(jmiNoviPolaznik);

        jmiPretragaPolaznika.setText("Pretraga polaznika");
        jmiPretragaPolaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaPolaznikaActionPerformed(evt);
            }
        });
        jmPolaznik.add(jmiPretragaPolaznika);

        jmbOsnovniMeni.add(jmPolaznik);

        jmZaposleni.setText("Zaposleni");

        jmiNoviZaposleni.setText("Novi zaposleni");
        jmiNoviZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNoviZaposleniActionPerformed(evt);
            }
        });
        jmZaposleni.add(jmiNoviZaposleni);

        jmiPretragaZaposlenih.setText("Pretraga zaposlenih");
        jmiPretragaZaposlenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaZaposlenihActionPerformed(evt);
            }
        });
        jmZaposleni.add(jmiPretragaZaposlenih);

        jmbOsnovniMeni.add(jmZaposleni);

        setJMenuBar(jmbOsnovniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiKrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKrajActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiKrajActionPerformed

    private void jmiUnosKursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKursaActionPerformed
        // TODO add your handling code here:
        FUnosKursa formaUnos = new FUnosKursa(this, false);
        formaUnos.setVisible(true);
    }//GEN-LAST:event_jmiUnosKursaActionPerformed

    private void jmiPretragaKursevaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaKursevaTabelaActionPerformed
        // TODO add your handling code here:
        FPretragaKursevaTabela formaTabela = new FPretragaKursevaTabela(this, false);
        formaTabela.setVisible(true);
    }//GEN-LAST:event_jmiPretragaKursevaTabelaActionPerformed

    private void jmiNoviPolaznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNoviPolaznikActionPerformed
        // TODO add your handling code here:
        FNoviPolaznik formaPolaznik = new FNoviPolaznik();
        //formaPolaznik.setAlwaysOnTop(true);
        formaPolaznik.setVisible(true);
    }//GEN-LAST:event_jmiNoviPolaznikActionPerformed

    private void jmiPretragaPolaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaPolaznikaActionPerformed
        // TODO add your handling code here:
        FPretragaPolaznika formaPretraga = new FPretragaPolaznika();
        //formaPretraga.setAlwaysOnTop(true);
        formaPretraga.setVisible(true);
    }//GEN-LAST:event_jmiPretragaPolaznikaActionPerformed

    private void jmiNoviZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNoviZaposleniActionPerformed
        // TODO add your handling code here:
        FNoviZaposleni f = new FNoviZaposleni();
        f.setVisible(true);
    }//GEN-LAST:event_jmiNoviZaposleniActionPerformed

    private void jmiPretragaZaposlenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaZaposlenihActionPerformed
        // TODO add your handling code here:
        FPretragaZaposlenih f = new FPretragaZaposlenih();
        f.setVisible(true);
    }//GEN-LAST:event_jmiPretragaZaposlenihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPocetna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmPocetak;
    private javax.swing.JMenu jmPolaznik;
    private javax.swing.JMenu jmZaposleni;
    private javax.swing.JMenuBar jmbOsnovniMeni;
    private javax.swing.JMenuItem jmiKraj;
    private javax.swing.JMenuItem jmiNoviPolaznik;
    private javax.swing.JMenuItem jmiNoviZaposleni;
    private javax.swing.JMenuItem jmiPretragaKursevaTabela;
    private javax.swing.JMenuItem jmiPretragaPolaznika;
    private javax.swing.JMenuItem jmiPretragaZaposlenih;
    private javax.swing.JMenuItem jmiUnosKursa;
    // End of variables declaration//GEN-END:variables

}
