/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zaposleni;

import forme.polaznik.*;
import domen.Zaposleni;
import forme.kurs.ki.KontrolorKIDajSveJezike;
import forme.polaznik.ki.KontrolorKIDajSvaMesta;
import forme.zaposleni.ki.KontrolorKINoviZaposleni;
import forme.zaposleni.ki.KontrolorKISacuvajZaposlenog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Dasa
 */
public class FNoviZaposleni extends javax.swing.JDialog {

    /**
     * Creates new form FNoviPolaznik
     */
    public FNoviZaposleni(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
        jlPolaznikID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtIme = new javax.swing.JTextField();
        jtxtPrezime = new javax.swing.JTextField();
        jtxtJMBG = new javax.swing.JTextField();
        jtxtBrojLK = new javax.swing.JTextField();
        jtxtUlica = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtBrojUlice = new javax.swing.JTextField();
        jcbbMesto = new javax.swing.JComboBox();
        jlGreskaIme = new javax.swing.JLabel();
        jlGreskaPrezime = new javax.swing.JLabel();
        jlGreskaJMBG = new javax.swing.JLabel();
        jlGreskaBrojLK = new javax.swing.JLabel();
        jlGreskaUlicaIBroj = new javax.swing.JLabel();
        jlGreskaMesto = new javax.swing.JLabel();
        jlGreskaTelefon = new javax.swing.JLabel();
        jlPolaznikID = new javax.swing.JLabel();
        jtxtTelefon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtRadnaKnjizica = new javax.swing.JTextField();
        jtxtZiroRacun = new javax.swing.JTextField();
        jlGreskaZiroRacun = new javax.swing.JLabel();
        jlGreskaRadnaKnjizica = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbbStraniJezik = new javax.swing.JComboBox();
        jlGreskaStraniJezik = new javax.swing.JLabel();
        jbtnNoviZaposleni = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnOmoguciIzmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Podaci o zaposlenom");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o zaposlenom"));

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("JMBG:");

        jLabel4.setText("Broj licne karte:");

        jLabel5.setText("Ulica:");

        jLabel6.setText("Mesto:");

        jLabel7.setText("Kontakt telefon:");

        jLabel8.setText("broj:");

        jlGreskaIme.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaIme.setText("*");

        jlGreskaPrezime.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaPrezime.setText("*");

        jlGreskaJMBG.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaJMBG.setText("*");

        jlGreskaBrojLK.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaBrojLK.setText("*");

        jlGreskaUlicaIBroj.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaUlicaIBroj.setText("*");

        jlGreskaMesto.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaMesto.setText("*");

        jlGreskaTelefon.setForeground(new java.awt.Color(155, 0, 0));
        jlGreskaTelefon.setText("*");

        jlPolaznikID.setText("jLabel9");

        jLabel9.setText("Radna knjizica:");

        jLabel10.setText("Ziro racun:");

        jlGreskaZiroRacun.setForeground(new java.awt.Color(155, 0, 0));
        jlGreskaZiroRacun.setText("*");

        jlGreskaRadnaKnjizica.setForeground(new java.awt.Color(155, 0, 0));
        jlGreskaRadnaKnjizica.setText("*");

        jLabel11.setText("Jezik:");

        jlGreskaStraniJezik.setForeground(new java.awt.Color(155, 0, 0));
        jlGreskaStraniJezik.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jlPolaznikID)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtJMBG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtBrojLK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtUlica, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtBrojUlice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbbMesto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtTelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtRadnaKnjizica)
                            .addComponent(jtxtPrezime)
                            .addComponent(jtxtIme)
                            .addComponent(jtxtZiroRacun)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlGreskaStraniJezik)
                                    .addComponent(jlGreskaRadnaKnjizica)
                                    .addComponent(jlGreskaZiroRacun)
                                    .addComponent(jlGreskaMesto)
                                    .addComponent(jlGreskaUlicaIBroj)
                                    .addComponent(jlGreskaBrojLK)
                                    .addComponent(jlGreskaJMBG)
                                    .addComponent(jlGreskaPrezime)
                                    .addComponent(jlGreskaIme))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jlGreskaTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(75, 75, 75)
                        .addComponent(jcbbStraniJezik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlGreskaIme))
                    .addComponent(jlPolaznikID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlGreskaPrezime)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaJMBG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaBrojLK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtBrojLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaUlicaIBroj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtBrojUlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaMesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaTelefon)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaRadnaKnjizica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtRadnaKnjizica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaZiroRacun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtZiroRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaStraniJezik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcbbStraniJezik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnNoviZaposleni.setText("Novi zaposleni");
        jbtnNoviZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoviZaposleniActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnOmoguciIzmenu.setText("Omoguci izmenu");
        jbtnOmoguciIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOmoguciIzmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnNoviZaposleni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jbtnOmoguciIzmenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNoviZaposleni)
                    .addComponent(jbtnOmoguciIzmenu)
                    .addComponent(jbtnSacuvaj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNoviZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoviZaposleniActionPerformed
        // TODO add your handling code here:
        KontrolorKINoviZaposleni.noviZaposleni(jlPolaznikID);
        omoguciUnos();
        jbtnNoviZaposleni.setVisible(false);
        jbtnOmoguciIzmenu.setVisible(false);
        jbtnSacuvaj.setVisible(true);
    }//GEN-LAST:event_jbtnNoviZaposleniActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        // TODO add your handling code here:
        KontrolorKISacuvajZaposlenog.sacuvajZaposlenog(jlPolaznikID, jtxtIme, jlGreskaIme, jtxtPrezime, jlGreskaPrezime,
                jtxtJMBG, jlGreskaJMBG, jtxtBrojLK, jlGreskaBrojLK, jtxtUlica, jtxtBrojUlice, jlGreskaUlicaIBroj,
                jcbbMesto, jlGreskaMesto, jtxtTelefon, jlGreskaTelefon, jtxtRadnaKnjizica, jlGreskaRadnaKnjizica,
                jtxtZiroRacun, jlGreskaZiroRacun, jcbbStraniJezik, jlGreskaStraniJezik, this);
        //this.dispose();
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnOmoguciIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOmoguciIzmenuActionPerformed
        // TODO add your handling code here:
        int opcija = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da izmenite podatke o zaposlenom?", "Izmena polaznika", JOptionPane.YES_NO_OPTION);
        if (opcija == 0) {
            omoguciUnos();
        }
    }//GEN-LAST:event_jbtnOmoguciIzmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FNoviPolaznik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FNoviPolaznik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FNoviPolaznik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FNoviPolaznik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FNoviPolaznik(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnNoviZaposleni;
    private javax.swing.JButton jbtnOmoguciIzmenu;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcbbMesto;
    private javax.swing.JComboBox jcbbStraniJezik;
    private javax.swing.JLabel jlGreskaBrojLK;
    private javax.swing.JLabel jlGreskaIme;
    private javax.swing.JLabel jlGreskaJMBG;
    private javax.swing.JLabel jlGreskaMesto;
    private javax.swing.JLabel jlGreskaPrezime;
    private javax.swing.JLabel jlGreskaRadnaKnjizica;
    private javax.swing.JLabel jlGreskaStraniJezik;
    private javax.swing.JLabel jlGreskaTelefon;
    private javax.swing.JLabel jlGreskaUlicaIBroj;
    private javax.swing.JLabel jlGreskaZiroRacun;
    private javax.swing.JLabel jlPolaznikID;
    private javax.swing.JTextField jtxtBrojLK;
    private javax.swing.JTextField jtxtBrojUlice;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtJMBG;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JTextField jtxtRadnaKnjizica;
    private javax.swing.JTextField jtxtTelefon;
    private javax.swing.JTextField jtxtUlica;
    private javax.swing.JTextField jtxtZiroRacun;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        KontrolorKIDajSvaMesta.dajSvaMesta(jcbbMesto);
        KontrolorKIDajSveJezike.dajSveJezike(jcbbStraniJezik);

        onemoguciUnos();

        jbtnNoviZaposleni.setVisible(true);
        jbtnNoviZaposleni.setEnabled(true);

        jbtnOmoguciIzmenu.setVisible(false);
        jbtnSacuvaj.setVisible(false);
    }

    public void onemoguciUnos() {
        jtxtIme.setEditable(false);
        jtxtPrezime.setEditable(false);
        jtxtJMBG.setEditable(false);
        jtxtBrojLK.setEditable(false);
        jtxtUlica.setEditable(false);
        jtxtBrojUlice.setEditable(false);
        jtxtTelefon.setEditable(false);
        jtxtRadnaKnjizica.setEditable(false);
        jtxtZiroRacun.setEditable(false);

        jcbbMesto.setEnabled(false);
        jcbbStraniJezik.setEnabled(false);

        jbtnSacuvaj.setEnabled(false);
        jbtnOmoguciIzmenu.setEnabled(true);
        jbtnNoviZaposleni.setEnabled(false);

        jbtnOmoguciIzmenu.setVisible(true);
        jbtnSacuvaj.setVisible(true);
        jbtnNoviZaposleni.setVisible(false);
    }

    public void omoguciUnos() {
        jtxtIme.setEditable(true);
        jtxtPrezime.setEditable(true);
        jtxtJMBG.setEditable(true);
        jtxtBrojLK.setEditable(true);
        jtxtUlica.setEditable(true);
        jtxtBrojUlice.setEditable(true);
        jtxtTelefon.setEditable(true);
        jtxtRadnaKnjizica.setEditable(true);
        jtxtZiroRacun.setEditable(true);

        jcbbMesto.setEnabled(true);
        jcbbStraniJezik.setEnabled(true);

        jbtnSacuvaj.setEnabled(true);
        jbtnOmoguciIzmenu.setEnabled(false);
        jbtnNoviZaposleni.setEnabled(false);

        jbtnSacuvaj.setVisible(true);
        jbtnOmoguciIzmenu.setVisible(false);
        jbtnNoviZaposleni.setVisible(false);
    }

    public void popuniPodatke(Zaposleni z) {
        jlPolaznikID.setText(z.getZaposleniID() + "");
        jtxtIme.setText(z.getIme());
        jtxtPrezime.setText(z.getPrezime());
        jtxtJMBG.setText(z.getJMBG());
        jtxtBrojLK.setText(z.getBrojLicneKarte());
        jtxtUlica.setText(z.getNazivUlice());
        jtxtBrojUlice.setText(z.getBrojUlice());
        jcbbMesto.setEditable(true);
        jcbbMesto.setSelectedItem(z.getMesto());
        jcbbMesto.setEditable(false);
        jtxtTelefon.setText(z.getBrojTelefona());
        jtxtRadnaKnjizica.setText(z.getBrojRadneKnjizice());
        jtxtZiroRacun.setText(z.getBrojZiroRacuna());
        jcbbStraniJezik.setEditable(true);
        jcbbStraniJezik.setSelectedItem(z.getJezik());
        jcbbStraniJezik.setEditable(false);
    }

    public void resetujFormu() {
        jlPolaznikID.setText("");
        jtxtIme.setText("");
        jlGreskaIme.setText("*");
        jtxtPrezime.setText("");
        jlGreskaPrezime.setText("*");
        jtxtJMBG.setText("");
        jlGreskaJMBG.setText("*");
        jtxtBrojLK.setText("");
        jlGreskaBrojLK.setText("*");
        jtxtUlica.setText("");
        jtxtBrojUlice.setText("");
        jlGreskaUlicaIBroj.setText("*");
        jcbbMesto.setSelectedIndex(0);
        jlGreskaMesto.setText("*");
        jtxtTelefon.setText("");
        jlGreskaTelefon.setText("*");
        jtxtRadnaKnjizica.setText("");
        jlGreskaRadnaKnjizica.setText("*");
        jtxtZiroRacun.setText("");
        jlGreskaZiroRacun.setText("*");
        jcbbStraniJezik.setSelectedIndex(0);
        jlGreskaStraniJezik.setText("*");
        
        onemoguciUnos();
        
        jbtnNoviZaposleni.setVisible(true);
        jbtnNoviZaposleni.setEnabled(true);

        jbtnOmoguciIzmenu.setVisible(false);
        jbtnSacuvaj.setVisible(false);
    }
}
