/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.polaznik;

import domen.Kurs;
import domen.Polaznik;
import domen.Ugovor;
import forme.polaznik.ki.KontrolorKIDajSvaMesta;
import forme.polaznik.ki.KontrolorKIDajSveKurseve;
import forme.polaznik.ki.KontrolorKINoviPolaznik;
import forme.polaznik.ki.KontrolorKISacuvajPolaznika;
import java.util.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import org.jdesktop.swingx.table.DatePickerCellEditor;
import tabela.model.ModelTabeleUgovori;

/**
 *
 * @author Dasa
 */
public class FNoviPolaznik extends javax.swing.JDialog {

    /**
     * Creates new form FNoviPolaznik
     */
    public FNoviPolaznik(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
        jlPolaznikID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtIme = new javax.swing.JTextField();
        jtxtPrezime = new javax.swing.JTextField();
        jtxtJMBG = new javax.swing.JTextField();
        jtxtBrojLK = new javax.swing.JTextField();
        jtxtUlica = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtBrojUlice = new javax.swing.JTextField();
        jcbbMesto = new javax.swing.JComboBox();
        jlGreskaIme = new javax.swing.JLabel();
        jlGreskaPrezime = new javax.swing.JLabel();
        jlGreskaJMBG = new javax.swing.JLabel();
        jlGreskaBrojLK = new javax.swing.JLabel();
        jlGreskaUlicaIBroj = new javax.swing.JLabel();
        jlGreskaMesto = new javax.swing.JLabel();
        jlGreskaTelefon = new javax.swing.JLabel();
        jlPolaznikID = new javax.swing.JLabel();
        jtxtTelefon = new javax.swing.JTextField();
        jbtnNoviPolaznik = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnOmoguciIzmenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUgovori = new javax.swing.JTable();
        jbtnNoviUgovor = new javax.swing.JButton();
        jbtnObrisiUgovor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Podaci o polazniku");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o polazniku"));

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("JMBG:");

        jLabel4.setText("Broj licne karte:");

        jLabel5.setText("Ulica:");

        jLabel6.setText("Mesto:");

        jLabel7.setText("Kontakt telefon:");

        jLabel8.setText("broj:");

        jlGreskaIme.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaIme.setText("*");

        jlGreskaPrezime.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaPrezime.setText("*");

        jlGreskaJMBG.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaJMBG.setText("*");

        jlGreskaBrojLK.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaBrojLK.setText("*");

        jlGreskaUlicaIBroj.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaUlicaIBroj.setText("*");

        jlGreskaMesto.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaMesto.setText("*");

        jlGreskaTelefon.setForeground(new java.awt.Color(153, 0, 0));
        jlGreskaTelefon.setText("*");

        jlPolaznikID.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jlPolaznikID))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbbMesto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBrojLK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtJMBG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtPrezime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtIme)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtUlica, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtBrojUlice, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlGreskaTelefon)
                            .addComponent(jlGreskaMesto)
                            .addComponent(jlGreskaBrojLK)
                            .addComponent(jlGreskaJMBG)
                            .addComponent(jlGreskaPrezime)
                            .addComponent(jlGreskaIme)
                            .addComponent(jlGreskaUlicaIBroj))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtxtTelefon))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlGreskaIme))
                    .addComponent(jlPolaznikID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlGreskaPrezime)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaJMBG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaBrojLK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtBrojLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaUlicaIBroj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtBrojUlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreskaMesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlGreskaTelefon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnNoviPolaznik.setText("Novi polaznik");
        jbtnNoviPolaznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoviPolaznikActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnOmoguciIzmenu.setText("Omoguci izmenu");
        jbtnOmoguciIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOmoguciIzmenuActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ugovori"));

        jtblUgovori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblUgovori);

        jbtnNoviUgovor.setText("+");
        jbtnNoviUgovor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoviUgovorActionPerformed(evt);
            }
        });

        jbtnObrisiUgovor.setText("-");
        jbtnObrisiUgovor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiUgovorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnNoviUgovor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnObrisiUgovor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNoviUgovor)
                    .addComponent(jbtnObrisiUgovor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnNoviPolaznik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnOmoguciIzmenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNoviPolaznik)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(jbtnOmoguciIzmenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNoviPolaznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoviPolaznikActionPerformed
        // TODO add your handling code here:
        KontrolorKINoviPolaznik.noviPolaznik(jlPolaznikID);
        omoguciUnos();
        jbtnNoviPolaznik.setVisible(false);
        jbtnOmoguciIzmenu.setVisible(false);
        jbtnSacuvaj.setVisible(true);

        Polaznik p = new Polaznik();
        p.setPolaznikID(Long.parseLong(jlPolaznikID.getText().trim()));
        ModelTabeleUgovori mtu = (ModelTabeleUgovori) jtblUgovori.getModel();
        mtu.setPolaznik(p);

        TableColumnModel tcm = jtblUgovori.getColumnModel();
        TableColumn tc1 = tcm.getColumn(6);
        tc1.setCellEditor(new DatePickerCellEditor());

        JComboBox jcbbKurs = new JComboBox();
        KontrolorKIDajSveKurseve.dajSveKurseve(jcbbKurs);
        jcbbKurs.setSelectedIndex(0);
        TableColumn tc2 = tcm.getColumn(1);
        tc2.setCellEditor(new DefaultCellEditor(jcbbKurs));
    }//GEN-LAST:event_jbtnNoviPolaznikActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        // TODO add your handling code here:
        KontrolorKISacuvajPolaznika.sacuvajPolaznika(jlPolaznikID, jtxtIme, jlGreskaIme, jtxtPrezime, jlGreskaPrezime,
                jtxtJMBG, jlGreskaJMBG, jtxtBrojLK, jlGreskaBrojLK, jtxtUlica, jtxtBrojUlice, jlGreskaUlicaIBroj,
                jcbbMesto, jlGreskaMesto, jtxtTelefon, jlGreskaTelefon, jtblUgovori);
        //this.dispose();
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnOmoguciIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOmoguciIzmenuActionPerformed
        // TODO add your handling code here:
        int opcija = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da izmenite podatke o polazniku?", "Izmena polaznika", JOptionPane.YES_NO_OPTION);
        if (opcija == 0) {
            omoguciUnos();
            TableColumnModel tcm = jtblUgovori.getColumnModel();
            TableColumn tc1 = tcm.getColumn(6);
            tc1.setCellEditor(new DatePickerCellEditor());

            JComboBox jcbbKurs = new JComboBox();
            KontrolorKIDajSveKurseve.dajSveKurseve(jcbbKurs);
            TableColumn tc2 = tcm.getColumn(1);
            tc2.setCellEditor(new DefaultCellEditor(jcbbKurs));
        }
    }//GEN-LAST:event_jbtnOmoguciIzmenuActionPerformed

    private void jbtnNoviUgovorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoviUgovorActionPerformed
        // TODO add your handling code here:
        ModelTabeleUgovori mtu = (ModelTabeleUgovori) jtblUgovori.getModel();
        Polaznik p = mtu.vratiPolaznika();
        Ugovor u = new Ugovor();
        u.setPolaznik(p);
        if (p.getUgovori().size() == 0) {
            u.setUgovorID(1);
        } else {
            u.setUgovorID(p.getUgovori().get(p.getUgovori().size() - 1).getUgovorID() + 1);
        }
        u.setBrojRata(0);
        u.setIznosRate(0);
        Kurs k = new Kurs();
        k.setKursID(1);
        u.setKurs(k);
        u.setRokZaSlRatu(new Date());
        u.setUkupnoPlaceno(0);
        u.setUkupnoPlacenoRata(0);
        mtu.dodajRed(u);
    }//GEN-LAST:event_jbtnNoviUgovorActionPerformed

    private void jbtnObrisiUgovorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiUgovorActionPerformed
        // TODO add your handling code here:
        ModelTabeleUgovori mtu = (ModelTabeleUgovori) jtblUgovori.getModel();
        int i = jtblUgovori.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Niste odarali nijedan ugovor!", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            mtu.obrisiRed(i);
        }
    }//GEN-LAST:event_jbtnObrisiUgovorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FNoviPolaznik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FNoviPolaznik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FNoviPolaznik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FNoviPolaznik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FNoviPolaznik(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnNoviPolaznik;
    private javax.swing.JButton jbtnNoviUgovor;
    private javax.swing.JButton jbtnObrisiUgovor;
    private javax.swing.JButton jbtnOmoguciIzmenu;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcbbMesto;
    private javax.swing.JLabel jlGreskaBrojLK;
    private javax.swing.JLabel jlGreskaIme;
    private javax.swing.JLabel jlGreskaJMBG;
    private javax.swing.JLabel jlGreskaMesto;
    private javax.swing.JLabel jlGreskaPrezime;
    private javax.swing.JLabel jlGreskaTelefon;
    private javax.swing.JLabel jlGreskaUlicaIBroj;
    private javax.swing.JLabel jlPolaznikID;
    private javax.swing.JTable jtblUgovori;
    private javax.swing.JTextField jtxtBrojLK;
    private javax.swing.JTextField jtxtBrojUlice;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtJMBG;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JTextField jtxtTelefon;
    private javax.swing.JTextField jtxtUlica;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        KontrolorKIDajSvaMesta.dajSvaMesta(jcbbMesto);

        onemoguciUnos();

        srediTabelu();

        jbtnNoviPolaznik.setVisible(true);
        jbtnNoviPolaznik.setEnabled(true);

        jbtnOmoguciIzmenu.setVisible(false);
        jbtnSacuvaj.setVisible(false);
    }

    public void srediTabelu() {
        Polaznik p = new Polaznik();
        ModelTabeleUgovori m = new ModelTabeleUgovori(p);
        jtblUgovori.setModel(m);

        jtblUgovori.getColumnModel().getColumn(0).setPreferredWidth(15);
        jtblUgovori.getColumnModel().getColumn(1).setPreferredWidth(300);
        jtblUgovori.getColumnModel().getColumn(2).setPreferredWidth(15);
        jtblUgovori.getColumnModel().getColumn(3).setPreferredWidth(65);
        jtblUgovori.getColumnModel().getColumn(4).setPreferredWidth(15);
        jtblUgovori.getColumnModel().getColumn(5).setPreferredWidth(65);
        jtblUgovori.getColumnModel().getColumn(6).setPreferredWidth(150);
    }

    public void onemoguciUnos() {
        jtxtIme.setEditable(false);
        jtxtPrezime.setEditable(false);
        jtxtJMBG.setEditable(false);
        jtxtBrojLK.setEditable(false);
        jtxtUlica.setEditable(false);
        jtxtBrojUlice.setEditable(false);
        jtxtTelefon.setEditable(false);

        jcbbMesto.setEnabled(false);

        jbtnSacuvaj.setEnabled(false);
        jbtnOmoguciIzmenu.setEnabled(true);
        jbtnNoviPolaznik.setEnabled(false);

        jbtnOmoguciIzmenu.setVisible(true);
        jbtnSacuvaj.setVisible(true);
        jbtnNoviPolaznik.setVisible(false);

        jbtnNoviUgovor.setEnabled(false);
        jbtnObrisiUgovor.setEnabled(false);

        jtblUgovori.setEnabled(false);
    }

    public void omoguciUnos() {
        jtxtIme.setEditable(true);
        jtxtPrezime.setEditable(true);
        jtxtJMBG.setEditable(true);
        jtxtBrojLK.setEditable(true);
        jtxtUlica.setEditable(true);
        jtxtBrojUlice.setEditable(true);
        jtxtTelefon.setEditable(true);

        jcbbMesto.setEnabled(true);

        jbtnSacuvaj.setEnabled(true);
        jbtnOmoguciIzmenu.setEnabled(false);
        jbtnNoviPolaznik.setEnabled(false);

        jbtnSacuvaj.setVisible(true);
        jbtnOmoguciIzmenu.setVisible(false);
        jbtnNoviPolaznik.setVisible(false);

        jbtnNoviUgovor.setEnabled(true);
        jbtnObrisiUgovor.setEnabled(true);

        jtblUgovori.setEnabled(true);
    }

    public void popuniPodatke(Polaznik p) {
        jlPolaznikID.setText(p.getPolaznikID() + "");
        jtxtIme.setText(p.getIme());
        jtxtPrezime.setText(p.getPrezime());
        jtxtJMBG.setText(p.getJMBG());
        jtxtBrojLK.setText(p.getBrojLicneKarte());
        jtxtUlica.setText(p.getNazivUlice());
        jtxtBrojUlice.setText(p.getBrojUlice());
        jcbbMesto.setEditable(true);
        jcbbMesto.setSelectedItem(p.getMesto());
        jcbbMesto.setEditable(false);
        jtxtTelefon.setText(p.getBrojTelefona());

        ModelTabeleUgovori mtu = ((ModelTabeleUgovori) jtblUgovori.getModel());
        mtu.setPolaznik(p);
    }
}
