/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kurs;

import domen.Kurs;
import forme.kurs.ki.KontrolorKIDajSveJezike;
import forme.kurs.ki.KontrolorKIDajSveNastavnike;
import forme.kurs.ki.KontrolorKIDajSveNivoe;
import forme.kurs.ki.KontrolorKINoviKurs;
import forme.kurs.ki.KontrolorKIObrisiKurs;
import forme.kurs.ki.KontrolorKISacuvajKurs;
import javax.swing.JOptionPane;

/**
 *
 * @author Dasa
 */
public class FUnosKursa extends javax.swing.JDialog {

    /**
     * Creates new form FUnosKursa
     */
    public FUnosKursa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
        jlKursID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPodaciOKursu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlKursID = new javax.swing.JLabel();
        jcbStraniJezik = new javax.swing.JComboBox();
        jcbNivo = new javax.swing.JComboBox();
        jcbNastavnik = new javax.swing.JComboBox();
        jtxtNazivUdzbenika = new javax.swing.JTextField();
        jtxtCenaKursa = new javax.swing.JTextField();
        jlStraniJezikGreska = new javax.swing.JLabel();
        jlNivoGreska = new javax.swing.JLabel();
        jlNastavnikGreska = new javax.swing.JLabel();
        jlFondCasovaGreska = new javax.swing.JLabel();
        jlTermin1Greska = new javax.swing.JLabel();
        jlTermin2Greska = new javax.swing.JLabel();
        jlDatumPocetkaGreska = new javax.swing.JLabel();
        jlDatumZavrsetkaGreska = new javax.swing.JLabel();
        jlNazivUdzbenikaGreska = new javax.swing.JLabel();
        jlCenaKursaGreska = new javax.swing.JLabel();
        jcbTermin1Dan = new javax.swing.JComboBox();
        jcbTermin2Dan = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtxtFondCasova = new javax.swing.JTextField();
        jspnTermin1Cas = new javax.swing.JSpinner();
        jspnTermin2Cas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jspnTermin1Min = new javax.swing.JSpinner();
        jspnTermin2Min = new javax.swing.JSpinner();
        jdpDatumPocetka = new org.jdesktop.swingx.JXDatePicker();
        jdpDatumZavrsetka = new org.jdesktop.swingx.JXDatePicker();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbSacuvaj = new javax.swing.JButton();
        jbIzmeni = new javax.swing.JButton();
        jbObrisi = new javax.swing.JButton();
        jbNoviKurs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Podaci o kursu");
        setResizable(false);

        jLabel2.setText("Strani jezik:");

        jLabel3.setText("Nivo:");

        jLabel4.setText("Nastavnik:");

        jLabel5.setText("Fond casova:");

        jLabel6.setText("Termin 1:");

        jLabel7.setText("Termin 2:");

        jLabel8.setText("Datum pocetka:");

        jLabel9.setText("Datum zavrsetka:");

        jLabel10.setText("Naziv udzbenika:");

        jLabel11.setText("Cena kursa:");

        jlStraniJezikGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlStraniJezikGreska.setText("*");

        jlNivoGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlNivoGreska.setText("*");

        jlNastavnikGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlNastavnikGreska.setText("*");

        jlFondCasovaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlFondCasovaGreska.setText("*");

        jlTermin1Greska.setForeground(new java.awt.Color(153, 0, 0));
        jlTermin1Greska.setText("*");

        jlTermin2Greska.setForeground(new java.awt.Color(153, 0, 0));
        jlTermin2Greska.setText("*");

        jlDatumPocetkaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlDatumPocetkaGreska.setText("*");

        jlDatumZavrsetkaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlDatumZavrsetkaGreska.setText("*");

        jlNazivUdzbenikaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlNazivUdzbenikaGreska.setText("*");

        jlCenaKursaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlCenaKursaGreska.setText("*");

        jcbTermin1Dan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ponedeljak", "Utorak", "Sreda", "Cetvrtak", "Petak", "Subota", "Nedelja" }));

        jcbTermin2Dan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ponedeljak", "Utorak", "Sreda", "Cetvrtak", "Petak", "Subota", "Nedelja" }));

        jLabel22.setText("u");

        jLabel23.setText("u");

        jLabel24.setText("casova");

        jLabel25.setText("casova");

        jspnTermin1Cas.setModel(new javax.swing.SpinnerNumberModel(8, 8, 21, 1));

        jspnTermin2Cas.setModel(new javax.swing.SpinnerNumberModel(8, 8, 21, 1));

        jLabel1.setText(":");

        jLabel12.setText(":");

        jspnTermin1Min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 15));

        jspnTermin2Min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 15));

        jLabel14.setText("sati");

        javax.swing.GroupLayout jpPodaciOKursuLayout = new javax.swing.GroupLayout(jpPodaciOKursu);
        jpPodaciOKursu.setLayout(jpPodaciOKursuLayout);
        jpPodaciOKursuLayout.setHorizontalGroup(
            jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(23, 23, 23)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcbNastavnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbNivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbStraniJezik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCenaKursaGreska)
                        .addComponent(jlNazivUdzbenikaGreska)
                        .addComponent(jlDatumZavrsetkaGreska)
                        .addComponent(jlDatumPocetkaGreska)
                        .addComponent(jlTermin2Greska)
                        .addComponent(jlTermin1Greska)
                        .addComponent(jlFondCasovaGreska)
                        .addComponent(jlNastavnikGreska)
                        .addComponent(jlNivoGreska)
                        .addComponent(jlStraniJezikGreska)
                        .addComponent(jtxtNazivUdzbenika)
                        .addComponent(jtxtCenaKursa)
                        .addComponent(jlKursID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                            .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jcbTermin1Dan, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                                .addComponent(jcbTermin2Dan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtFondCasova, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                    .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jspnTermin2Cas))
                                        .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jspnTermin1Cas)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jspnTermin2Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                        .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jspnTermin1Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jdpDatumZavrsetka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(jdpDatumPocetka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpPodaciOKursuLayout.setVerticalGroup(
            jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlKursID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlStraniJezikGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbStraniJezik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNivoGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbNivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNastavnikGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbNastavnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlFondCasovaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtFondCasova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTermin1Greska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbTermin1Dan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jspnTermin1Cas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jspnTermin1Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTermin2Greska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbTermin2Dan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jspnTermin2Cas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jspnTermin2Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDatumPocetkaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jdpDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDatumZavrsetkaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jdpDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNazivUdzbenikaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtNazivUdzbenika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCenaKursaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtCenaKursa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSacuvaj.setText("Sacuvaj");
        jbSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSacuvajActionPerformed(evt);
            }
        });

        jbIzmeni.setText("Omoguci izmenu");
        jbIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIzmeniActionPerformed(evt);
            }
        });

        jbObrisi.setText("Obrisi");
        jbObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbObrisiActionPerformed(evt);
            }
        });

        jbNoviKurs.setText("Novi kurs");
        jbNoviKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNoviKursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNoviKurs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jbIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSacuvaj)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSacuvaj)
                    .addComponent(jbIzmeni)
                    .addComponent(jbObrisi)
                    .addComponent(jbNoviKurs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPodaciOKursu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPodaciOKursu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSacuvajActionPerformed
        // TODO add your handling code here:
        KontrolorKISacuvajKurs.sacuvajKurs(this, jlKursID, jcbStraniJezik, jlStraniJezikGreska, jcbNivo, jlNivoGreska, jcbNastavnik, jlNastavnikGreska, jtxtFondCasova, jlFondCasovaGreska, jcbTermin1Dan, jlTermin1Greska, jspnTermin1Cas, jspnTermin1Min, jcbTermin2Dan, jlTermin2Greska, jspnTermin2Cas, jspnTermin2Min, jdpDatumPocetka, jlDatumPocetkaGreska, jdpDatumZavrsetka, jlDatumZavrsetkaGreska, jtxtNazivUdzbenika, jlNazivUdzbenikaGreska, jtxtCenaKursa, jlCenaKursaGreska);
        //this.dispose();
    }//GEN-LAST:event_jbSacuvajActionPerformed

    private void jbIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIzmeniActionPerformed
        // TODO add your handling code here:
        int opcija = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da izmenite podatke o kursu?", "Izmena kursa", JOptionPane.YES_NO_OPTION);
        if (opcija == 0) {
            omoguciUnos();
        }
    }//GEN-LAST:event_jbIzmeniActionPerformed

    private void jbObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbObrisiActionPerformed
        // TODO add your handling code here:
        int opcija = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete kurs?", "Brisanje kursa", JOptionPane.YES_NO_OPTION);
        if (opcija == 0) {
            KontrolorKIObrisiKurs.obrisiKurs(jlKursID);
            this.dispose();
        }
    }//GEN-LAST:event_jbObrisiActionPerformed

    private void jbNoviKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNoviKursActionPerformed
        // TODO add your handling code here:
        KontrolorKINoviKurs.noviKurs(jlKursID);
        omoguciUnos();
        jbNoviKurs.setVisible(false);
        jbObrisi.setVisible(false);
        jbIzmeni.setVisible(false);
        jbSacuvaj.setVisible(true);
    }//GEN-LAST:event_jbNoviKursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FUnosKursa dialog = new FUnosKursa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbIzmeni;
    private javax.swing.JButton jbNoviKurs;
    private javax.swing.JButton jbObrisi;
    private javax.swing.JButton jbSacuvaj;
    private javax.swing.JComboBox jcbNastavnik;
    private javax.swing.JComboBox jcbNivo;
    private javax.swing.JComboBox jcbStraniJezik;
    private javax.swing.JComboBox jcbTermin1Dan;
    private javax.swing.JComboBox jcbTermin2Dan;
    private org.jdesktop.swingx.JXDatePicker jdpDatumPocetka;
    private org.jdesktop.swingx.JXDatePicker jdpDatumZavrsetka;
    private javax.swing.JLabel jlCenaKursaGreska;
    private javax.swing.JLabel jlDatumPocetkaGreska;
    private javax.swing.JLabel jlDatumZavrsetkaGreska;
    private javax.swing.JLabel jlFondCasovaGreska;
    private javax.swing.JLabel jlKursID;
    private javax.swing.JLabel jlNastavnikGreska;
    private javax.swing.JLabel jlNazivUdzbenikaGreska;
    private javax.swing.JLabel jlNivoGreska;
    private javax.swing.JLabel jlStraniJezikGreska;
    private javax.swing.JLabel jlTermin1Greska;
    private javax.swing.JLabel jlTermin2Greska;
    private javax.swing.JPanel jpPodaciOKursu;
    private javax.swing.JSpinner jspnTermin1Cas;
    private javax.swing.JSpinner jspnTermin1Min;
    private javax.swing.JSpinner jspnTermin2Cas;
    private javax.swing.JSpinner jspnTermin2Min;
    private javax.swing.JTextField jtxtCenaKursa;
    private javax.swing.JTextField jtxtFondCasova;
    private javax.swing.JTextField jtxtNazivUdzbenika;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        KontrolorKIDajSveJezike.dajSveJezike(jcbStraniJezik);
        KontrolorKIDajSveNivoe.dajSveNivoe(jcbNivo);
        KontrolorKIDajSveNastavnike.dajSveNastavnike(jcbNastavnik);

        onemoguciUnos();
        
        jbNoviKurs.setVisible(true);
        jbNoviKurs.setEnabled(true);
        
        jbIzmeni.setVisible(false);
        jbObrisi.setVisible(false);
        jbSacuvaj.setVisible(false);        
    }

    public void popuniPodatke(Kurs kurs) {
        jlKursID.setText(kurs.getKursID() + "");
        jcbStraniJezik.setEditable(true);
        jcbStraniJezik.getModel().setSelectedItem(kurs.getJezik());
        jcbStraniJezik.setEditable(false);
        jcbNivo.setEditable(true);
        jcbNivo.getModel().setSelectedItem(kurs.getNivo());
        jcbNivo.setEditable(false);
        jcbNastavnik.setEditable(true);
        jcbNastavnik.getModel().setSelectedItem(kurs.getNastavnik());
        jcbNastavnik.setEditable(false);
        jtxtFondCasova.setText(kurs.getFondCasova() + "");
        String[] d1 = kurs.getTermin1().split(" ");
        jcbTermin1Dan.setEditable(true);
        jcbTermin1Dan.getModel().setSelectedItem(d1[0]);
        jcbTermin1Dan.setEditable(false);
        String[] vreme1 = d1[1].split(":");
        jspnTermin1Cas.setValue(Integer.parseInt(vreme1[0]));
        jspnTermin1Min.setValue(Integer.parseInt(vreme1[1]));
        String[] d2 = kurs.getTermin2().split(" ");
        jcbTermin2Dan.setEditable(true);
        jcbTermin2Dan.getModel().setSelectedItem(d2[0]);
        jcbTermin2Dan.setEditable(false);
        String[] vreme2 = d2[1].split(":");
        jspnTermin2Cas.setValue(Integer.parseInt(vreme2[0]));
        jspnTermin2Min.setValue(Integer.parseInt(vreme2[1]));
        jdpDatumPocetka.setDate(kurs.getDatumOd());
        jdpDatumZavrsetka.setDate(kurs.getDatumDo());
        jtxtNazivUdzbenika.setText(kurs.getNazivUdzbenika());
        jtxtCenaKursa.setText(kurs.getCena() + "");
    }

    public void onemoguciUnos() {
        jcbStraniJezik.setEnabled(false);
        jcbNivo.setEnabled(false);
        jcbNastavnik.setEnabled(false);
        jcbTermin1Dan.setEnabled(false);
        jcbTermin2Dan.setEnabled(false);

        jtxtFondCasova.setEditable(false);
        jspnTermin1Cas.setEnabled(false);
        jspnTermin1Min.setEnabled(false);
        jspnTermin2Cas.setEnabled(false);
        jspnTermin2Min.setEnabled(false);
        jtxtNazivUdzbenika.setEditable(false);
        jtxtCenaKursa.setEditable(false);

        jdpDatumPocetka.setEditable(false);
        jdpDatumZavrsetka.setEditable(false);

        jbSacuvaj.setEnabled(false);
        jbIzmeni.setEnabled(true);
        jbObrisi.setEnabled(true);
        jbNoviKurs.setEnabled(false);        
        
        jbIzmeni.setVisible(true);
        jbObrisi.setVisible(true);
        jbSacuvaj.setVisible(true);
        jbNoviKurs.setVisible(false);
    }

    public void omoguciUnos() {
        jcbStraniJezik.setEnabled(true);
        jcbNivo.setEnabled(true);
        jcbNastavnik.setEnabled(true);
        jcbTermin1Dan.setEnabled(true);
        jcbTermin2Dan.setEnabled(true);

        jtxtFondCasova.setEditable(true);
        jspnTermin1Cas.setEnabled(true);
        jspnTermin1Min.setEnabled(true);
        jspnTermin2Cas.setEnabled(true);
        jspnTermin2Min.setEnabled(true);
        jtxtNazivUdzbenika.setEditable(true);
        jtxtCenaKursa.setEditable(true);

        jdpDatumPocetka.setEditable(true);
        jdpDatumZavrsetka.setEditable(true);

        jbSacuvaj.setEnabled(true);
        jbIzmeni.setEnabled(false);
        jbObrisi.setEnabled(false);
        jbNoviKurs.setEnabled(false);
        
        jbSacuvaj.setVisible(true);
        jbIzmeni.setVisible(false);
        jbObrisi.setVisible(false);
        jbNoviKurs.setVisible(false);
    }
    
    public void ocistiFormu(){
        jlKursID.setText("");
        jcbStraniJezik.setSelectedIndex(0);
        jlStraniJezikGreska.setText("*");
        jcbNivo.setSelectedIndex(0); 
        jlNivoGreska.setText("*");
        jcbNastavnik.setSelectedIndex(0);
        jlNastavnikGreska.setText("*"); 
        jtxtFondCasova.setText(""); 
        jlFondCasovaGreska.setText("*"); 
        jcbTermin1Dan.setSelectedIndex(0); 
        jlTermin1Greska.setText("*"); 
        jspnTermin1Cas.setValue(8);
        jspnTermin1Min.setValue(0);
        jcbTermin2Dan.setSelectedIndex(0);
        jlTermin2Greska.setText("*"); 
        jspnTermin2Cas.setValue(8);
        jspnTermin2Min.setValue(0);
        jdpDatumPocetka.setDate(null);
        jlDatumPocetkaGreska.setText("*"); 
        jdpDatumZavrsetka.setDate(null);
        jlDatumZavrsetkaGreska.setText("*"); 
        jtxtNazivUdzbenika.setText(""); 
        jlNazivUdzbenikaGreska.setText("*"); 
        jtxtCenaKursa.setText("");
        jlCenaKursaGreska.setText("*");
        
        onemoguciUnos();
        
        jbNoviKurs.setVisible(true);
        jbNoviKurs.setEnabled(true);
        
        jbIzmeni.setVisible(false);
        jbObrisi.setVisible(false);
        jbSacuvaj.setVisible(false); 
    }
    
}
