/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kurs;

/**
 *
 * @author Dasa
 */
public class FPocetnaKurs extends javax.swing.JFrame {

    /**
     * Creates new form FPocetnaKurs
     */
    public FPocetnaKurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmbOsnovniMeni = new javax.swing.JMenuBar();
        jmPocetak = new javax.swing.JMenu();
        jmiUnosKursa = new javax.swing.JMenuItem();
        jmiPretragaKurseva = new javax.swing.JMenuItem();
        jmiPretragaKursevaTabela = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiKraj = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Skola stranih jezika");
        setAlwaysOnTop(true);

        jmPocetak.setText("Pocetak");

        jmiUnosKursa.setText("Novi kurs");
        jmiUnosKursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKursaActionPerformed(evt);
            }
        });
        jmPocetak.add(jmiUnosKursa);

        jmiPretragaKurseva.setText("Pretraga kurseva");
        jmiPretragaKurseva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaKursevaActionPerformed(evt);
            }
        });
        jmPocetak.add(jmiPretragaKurseva);

        jmiPretragaKursevaTabela.setText("Pretraga kurseva - tabela");
        jmiPretragaKursevaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaKursevaTabelaActionPerformed(evt);
            }
        });
        jmPocetak.add(jmiPretragaKursevaTabela);
        jmPocetak.add(jSeparator1);

        jmiKraj.setText("Kraj");
        jmiKraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKrajActionPerformed(evt);
            }
        });
        jmPocetak.add(jmiKraj);

        jmbOsnovniMeni.add(jmPocetak);

        setJMenuBar(jmbOsnovniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiKrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKrajActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiKrajActionPerformed

    private void jmiUnosKursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKursaActionPerformed
        // TODO add your handling code here:
        FUnosKursa formaUnos = new FUnosKursa(this, true);
        formaUnos.noviKurs();
        formaUnos.setVisible(true);
    }//GEN-LAST:event_jmiUnosKursaActionPerformed

    private void jmiPretragaKursevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaKursevaActionPerformed
        // TODO add your handling code here:
        FPretragaKurseva formaPretraga = new FPretragaKurseva(this, true);
        formaPretraga.setVisible(true);
    }//GEN-LAST:event_jmiPretragaKursevaActionPerformed

    private void jmiPretragaKursevaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaKursevaTabelaActionPerformed
        // TODO add your handling code here:
        FPretragaKursevaTabela formaTabela = new FPretragaKursevaTabela(this, true);
        formaTabela.setVisible(true);
    }//GEN-LAST:event_jmiPretragaKursevaTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPocetnaKurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPocetnaKurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPocetnaKurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPocetnaKurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPocetnaKurs().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmPocetak;
    private javax.swing.JMenuBar jmbOsnovniMeni;
    private javax.swing.JMenuItem jmiKraj;
    private javax.swing.JMenuItem jmiPretragaKurseva;
    private javax.swing.JMenuItem jmiPretragaKursevaTabela;
    private javax.swing.JMenuItem jmiUnosKursa;
    // End of variables declaration//GEN-END:variables
}
