/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kurs;

import domen.Kurs;
import domen.Nivo;
import domen.StraniJezik;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontekst.Kontekst;
import kontroler.Kontroler;
import tabela.model.ModelTabeleKurs;

/**
 *
 * @author Dasa
 */
public class FPretragaKursevaTabela extends javax.swing.JDialog {

    /**
     * Creates new form FPretragaKursevaTabela
     */
    public FPretragaKursevaTabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
        popuniTabeluKurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFilteri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbStraniJezik = new javax.swing.JComboBox();
        jcbNivo = new javax.swing.JComboBox();
        jbPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblKurs = new javax.swing.JTable();
        jbtnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setText("Strani jezik:");

        jLabel2.setText("Nivo:");

        jbPretrazi.setText("Pretrazi");
        jbPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFilteriLayout = new javax.swing.GroupLayout(jpFilteri);
        jpFilteri.setLayout(jpFilteriLayout);
        jpFilteriLayout.setHorizontalGroup(
            jpFilteriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFilteriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFilteriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpFilteriLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFilteriLayout.createSequentialGroup()
                        .addGroup(jpFilteriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jpFilteriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbStraniJezik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbNivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpFilteriLayout.setVerticalGroup(
            jpFilteriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFilteriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFilteriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbStraniJezik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFilteriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbNivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbPretrazi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtblKurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblKurs);

        jbtnDetalji.setText("Prikazi detalje");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFilteri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnDetalji)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFilteri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnDetalji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPretraziActionPerformed
        // TODO add your handling code here:
        osveziPrikaz();
    }//GEN-LAST:event_jbPretraziActionPerformed

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        try {
            int id = Integer.parseInt(jtblKurs.getValueAt(jtblKurs.getSelectedRow(), 0).toString());
            Kurs k = new Kurs();
            k.setKursID(id);
            Kurs kurs = Kontroler.vratiInstancu().pronadjiKurs(k);
            if (kurs == null) {
                JOptionPane.showMessageDialog(this, "Niste izabrali nijedan kurs iz tabele!", "Greska", JOptionPane.ERROR_MESSAGE);
            } else {
                FUnosKursa formaPrikaz = new FUnosKursa((JFrame) this.getParent(), true);
                formaPrikaz.popuniPodatke(kurs);
                formaPrikaz.onemoguciUnos();
                formaPrikaz.setVisible(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju kursa: "+ex.getMessage());
        }
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        //osveziPrikaz();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPretragaKursevaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPretragaKursevaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPretragaKursevaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPretragaKursevaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FPretragaKursevaTabela dialog = new FPretragaKursevaTabela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbPretrazi;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JComboBox jcbNivo;
    private javax.swing.JComboBox jcbStraniJezik;
    private javax.swing.JPanel jpFilteri;
    private javax.swing.JTable jtblKurs;
    // End of variables declaration//GEN-END:variables

    private void popuniCBStraniJezici() {
        try {
            List<StraniJezik> lista = Kontroler.vratiInstancu().dajStraneJezike();
            for (StraniJezik straniJezik : lista) {
                jcbStraniJezik.addItem(straniJezik);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju stranih jezika!");
        }
    }

    private void popuniCBNivo() {
        try {
            List<Nivo> lista = Kontroler.vratiInstancu().dajNivoe();
            for (Nivo nivo : lista) {
                jcbNivo.addItem(nivo);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju nivoa!");
        }
    }

    private void srediFormu() {
        popuniCBStraniJezici();
        popuniCBNivo();
    }

    private void popuniTabeluKurs() {
        List<Kurs> k = new ArrayList<>();
        ModelTabeleKurs m = new ModelTabeleKurs(k);
        jtblKurs.setModel(m);
    }

    private void osveziPrikaz() {
        try {
            StraniJezik sj = (StraniJezik) jcbStraniJezik.getSelectedItem();
            Nivo n = (Nivo) jcbNivo.getSelectedItem();
            Kurs k = new Kurs();
            k.setJezik(sj);
            k.setNivo(n);
            List<Kurs> listaKurseva = Kontroler.vratiInstancu().pretraziKurseve(k);

            ModelTabeleKurs m = new ModelTabeleKurs(listaKurseva);
            jtblKurs.setModel(m);
            JOptionPane.showMessageDialog(this, "Sistem je pronasao kurseve po zadatoj vrednosti!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
