/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.kurs;

import domen.Kurs;
import domen.Nivo;
import domen.StraniJezik;
import domen.Zaposleni;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author Dasa
 */
public class FUnosKursa extends javax.swing.JDialog {

    /**
     * Creates new form FUnosKursa
     */
    public FUnosKursa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPodaciOKursu = new javax.swing.JPanel();
        jlKursIDLabela = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlKursID = new javax.swing.JLabel();
        jcbStraniJezik = new javax.swing.JComboBox();
        jcbNivo = new javax.swing.JComboBox();
        jcbNastavnik = new javax.swing.JComboBox();
        jspnDatumPocetka = new javax.swing.JSpinner();
        jspnDatumZavrsetka = new javax.swing.JSpinner();
        jtxtNazivUdzbenika = new javax.swing.JTextField();
        jtxtCenaKursa = new javax.swing.JTextField();
        jlStraniJezikGreska = new javax.swing.JLabel();
        jlNivoGreska = new javax.swing.JLabel();
        jlNastavnikGreska = new javax.swing.JLabel();
        jlFondCasovaGreska = new javax.swing.JLabel();
        jlTermin1Greska = new javax.swing.JLabel();
        jlTermin2Greska = new javax.swing.JLabel();
        jlDatumPocetkaGreska = new javax.swing.JLabel();
        jlDatumZavrsetkaGreska = new javax.swing.JLabel();
        jlNazivUdzbenikaGreska = new javax.swing.JLabel();
        jlCenaKursaGreska = new javax.swing.JLabel();
        jcbTermin1Dan = new javax.swing.JComboBox();
        jcbTermin2Dan = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtxtFondCasova = new javax.swing.JTextField();
        jspnTermin1Cas = new javax.swing.JSpinner();
        jspnTermin2Cas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jspnTermin1Min = new javax.swing.JSpinner();
        jspnTermin2Min = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jbSacuvaj = new javax.swing.JButton();
        jbIzmeni = new javax.swing.JButton();
        jbObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos podataka o kursu");
        setResizable(false);

        jlKursIDLabela.setText("Kurs ID:");

        jLabel2.setText("Strani jezik:");

        jLabel3.setText("Nivo:");

        jLabel4.setText("Nastavnik:");

        jLabel5.setText("Fond casova:");

        jLabel6.setText("Termin 1:");

        jLabel7.setText("Termin 2:");

        jLabel8.setText("Datum pocetka:");

        jLabel9.setText("Datum zavrsetka:");

        jLabel10.setText("Naziv udzbenika:");

        jLabel11.setText("Cena kursa:");

        jspnDatumPocetka.setModel(new javax.swing.SpinnerDateModel());

        jspnDatumZavrsetka.setModel(new javax.swing.SpinnerDateModel());

        jlStraniJezikGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlStraniJezikGreska.setText("*");

        jlNivoGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlNivoGreska.setText("*");

        jlNastavnikGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlNastavnikGreska.setText("*");

        jlFondCasovaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlFondCasovaGreska.setText("*");

        jlTermin1Greska.setForeground(new java.awt.Color(153, 0, 0));
        jlTermin1Greska.setText("*");

        jlTermin2Greska.setForeground(new java.awt.Color(153, 0, 0));
        jlTermin2Greska.setText("*");

        jlDatumPocetkaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlDatumPocetkaGreska.setText("*");

        jlDatumZavrsetkaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlDatumZavrsetkaGreska.setText("*");

        jlNazivUdzbenikaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlNazivUdzbenikaGreska.setText("*");

        jlCenaKursaGreska.setForeground(new java.awt.Color(153, 0, 0));
        jlCenaKursaGreska.setText("*");

        jcbTermin1Dan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ponedeljak", "Utorak", "Sreda", "Cetvrtak", "Petak", "Subota", "Nedelja" }));

        jcbTermin2Dan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ponedeljak", "Utorak", "Sreda", "Cetvrtak", "Petak", "Subota", "Nedelja" }));

        jLabel22.setText("u");

        jLabel23.setText("u");

        jLabel24.setText("casova");

        jLabel25.setText("casova");

        jspnTermin1Cas.setModel(new javax.swing.SpinnerNumberModel(8, 8, 21, 1));

        jspnTermin2Cas.setModel(new javax.swing.SpinnerNumberModel(8, 8, 21, 1));

        jLabel1.setText(":");

        jLabel12.setText(":");

        jspnTermin1Min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 15));

        jspnTermin2Min.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 15));

        javax.swing.GroupLayout jpPodaciOKursuLayout = new javax.swing.GroupLayout(jpPodaciOKursu);
        jpPodaciOKursu.setLayout(jpPodaciOKursuLayout);
        jpPodaciOKursuLayout.setHorizontalGroup(
            jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlKursIDLabela)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(23, 23, 23)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                        .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbTermin1Dan, 0, 100, Short.MAX_VALUE)
                            .addComponent(jcbTermin2Dan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspnTermin2Cas))
                            .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspnTermin1Cas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspnTermin2Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                            .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspnTermin1Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jcbNastavnik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbNivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbStraniJezik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCenaKursaGreska)
                    .addComponent(jlNazivUdzbenikaGreska)
                    .addComponent(jlDatumZavrsetkaGreska)
                    .addComponent(jlDatumPocetkaGreska)
                    .addComponent(jlTermin2Greska)
                    .addComponent(jlTermin1Greska)
                    .addComponent(jlFondCasovaGreska)
                    .addComponent(jlNastavnikGreska)
                    .addComponent(jlNivoGreska)
                    .addComponent(jlStraniJezikGreska)
                    .addComponent(jtxtFondCasova, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspnDatumPocetka)
                    .addComponent(jspnDatumZavrsetka)
                    .addComponent(jtxtNazivUdzbenika)
                    .addComponent(jtxtCenaKursa)
                    .addComponent(jlKursID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpPodaciOKursuLayout.setVerticalGroup(
            jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPodaciOKursuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlKursIDLabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlKursID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jlStraniJezikGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbStraniJezik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNivoGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbNivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNastavnikGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbNastavnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlFondCasovaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtFondCasova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTermin1Greska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbTermin1Dan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jspnTermin1Cas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jspnTermin1Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTermin2Greska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbTermin2Dan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jspnTermin2Cas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jspnTermin2Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDatumPocetkaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jspnDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDatumZavrsetkaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jspnDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNazivUdzbenikaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtNazivUdzbenika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCenaKursaGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPodaciOKursuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtCenaKursa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSacuvaj.setText("Sacuvaj");
        jbSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSacuvajActionPerformed(evt);
            }
        });

        jbIzmeni.setText("Izmeni");
        jbIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIzmeniActionPerformed(evt);
            }
        });

        jbObrisi.setText("Obrisi");
        jbObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jbObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSacuvaj)
                    .addComponent(jbIzmeni)
                    .addComponent(jbObrisi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPodaciOKursu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPodaciOKursu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSacuvajActionPerformed
        // TODO add your handling code here:
        try {
            long kursID = Long.parseLong(jlKursID.getText().trim());
            StraniJezik straniJezik = (StraniJezik) jcbStraniJezik.getSelectedItem();
            if (straniJezik == null) {
                jlStraniJezikGreska.setText("Strani jezik je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlStraniJezikGreska.setText("*");
            }
            Nivo nivo = (Nivo) jcbNivo.getSelectedItem();
            if (nivo == null) {
                jlNivoGreska.setText("Nivo je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlNivoGreska.setText("*");
            }
            Zaposleni nastavnik = (Zaposleni) jcbNastavnik.getSelectedItem();
            if (nastavnik == null) {
                jlNastavnikGreska.setText("Nastavnik je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlNastavnikGreska.setText("*");
            }
            String sFondCasova = (String) jtxtFondCasova.getText().trim();
            int fondCasova = 10;
            if (sFondCasova.isEmpty()) {
                jlFondCasovaGreska.setText("Fond casova je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                fondCasova = Integer.parseInt(sFondCasova);
                if (fondCasova <= 10) {
                    jlFondCasovaGreska.setText("Fond casova mora biti veci od 10!");
                    throw new Exception("Nisu ispravno uneti podaci!");
                } else {
                    jlFondCasovaGreska.setText("*");
                }
            }
            String t1dan = (String) jcbTermin1Dan.getSelectedItem();
            if (t1dan.isEmpty()) {
                jlTermin1Greska.setText("Dan prvog termina je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlTermin1Greska.setText("*");
            }
            String t1cas = jspnTermin1Cas.getValue().toString();
            if (t1cas.isEmpty()) {
                jlTermin1Greska.setText("Vreme prvog termina je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlTermin1Greska.setText("*");
            }
            String t1min = jspnTermin1Min.getValue().toString();
            if (t1min.isEmpty()) {
                jlTermin1Greska.setText("Vreme prvog termina je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlTermin1Greska.setText("*");
            }
            String t2dan = (String) jcbTermin2Dan.getSelectedItem();
            if (t2dan.isEmpty()) {
                jlTermin2Greska.setText("Dan drugog termina je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlTermin2Greska.setText("*");
            }
            String t2cas = jspnTermin2Cas.getValue().toString();
            if (t2cas.isEmpty()) {
                jlTermin2Greska.setText("Vreme drugog termina je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlTermin2Greska.setText("*");
            }
            String t2min = jspnTermin2Min.getValue().toString();
            if (t2min.isEmpty()) {
                jlTermin2Greska.setText("Vreme drugog termina je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlTermin2Greska.setText("*");
            }
            Date datumOd = (Date) jspnDatumPocetka.getValue();
            if (datumOd == null) {
                jlDatumPocetkaGreska.setText("Datum pocetka je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlDatumPocetkaGreska.setText("*");
            }
            Date datumDo = (Date) jspnDatumZavrsetka.getValue();
            if (datumDo == null) {
                jlDatumZavrsetkaGreska.setText("Datum zavrsetka je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlDatumZavrsetkaGreska.setText("*");
            }
            String nazivUdzbenika = jtxtNazivUdzbenika.getText().trim();
            if (nazivUdzbenika.isEmpty()) {
                jlNazivUdzbenikaGreska.setText("Naziv udzbenika je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                jlNazivUdzbenikaGreska.setText("*");
            }
            String sCenaKursa = jtxtCenaKursa.getText().trim();
            int cenaKursa = 0;
            if (sCenaKursa.isEmpty()) {
                jlCenaKursaGreska.setText("Cena kursa je obavezno polje!");
                throw new Exception("Nisu ispravno uneti podaci!");
            } else {
                cenaKursa = Integer.parseInt(sCenaKursa);
                if (cenaKursa < 0) {
                    jlCenaKursaGreska.setText("Cena kursa je mora biti veca od 0!");
                    throw new Exception("Nisu ispravno uneti podaci!");
                } else {
                    jlCenaKursaGreska.setText("*");
                }
            }

            Kurs k = new Kurs();
            k.setKursID(kursID);
            k.setFondCasova(fondCasova);
            k.setCena(cenaKursa);
            k.setDatumOd(datumOd);
            k.setDatumDo(datumDo);
            k.setTermin1(t1dan + " " + t1cas + ":" + t1min);
            k.setTermin2(t2dan + " " + t2cas + ":" + t2min);
            k.setNazivUdzbenika(nazivUdzbenika);
            k.setJezik(straniJezik);
            k.setNivo(nivo);
            k.setNastavnik(nastavnik);
            
            Kontroler.vratiInstancu().zapamtiKurs(k);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio podatke o kursu!", "Uspesan unos", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSacuvajActionPerformed

    private void jbIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIzmeniActionPerformed
        // TODO add your handling code here:
        int opcija = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da izmenite podatke o kursu?", "Izmena kursa", JOptionPane.YES_NO_OPTION);
        if (opcija == 0) {
            omoguciUnos();
        }
    }//GEN-LAST:event_jbIzmeniActionPerformed

    private void jbObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbObrisiActionPerformed
        // TODO add your handling code here:
        int opcija = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete kurs?", "Brisanje kursa", JOptionPane.YES_NO_OPTION);
        if (opcija == 0) {
            long kursID = Long.parseLong(jlKursID.getText().trim());
            Kurs kurs = new Kurs();
            kurs.setKursID(kursID);
            try {
                Kontroler.vratiInstancu().obrisiKurs(kurs);
                JOptionPane.showMessageDialog(this, "Sistem je obrisao kurs!");
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUnosKursa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FUnosKursa dialog = new FUnosKursa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbIzmeni;
    private javax.swing.JButton jbObrisi;
    private javax.swing.JButton jbSacuvaj;
    private javax.swing.JComboBox jcbNastavnik;
    private javax.swing.JComboBox jcbNivo;
    private javax.swing.JComboBox jcbStraniJezik;
    private javax.swing.JComboBox jcbTermin1Dan;
    private javax.swing.JComboBox jcbTermin2Dan;
    private javax.swing.JLabel jlCenaKursaGreska;
    private javax.swing.JLabel jlDatumPocetkaGreska;
    private javax.swing.JLabel jlDatumZavrsetkaGreska;
    private javax.swing.JLabel jlFondCasovaGreska;
    private javax.swing.JLabel jlKursID;
    private javax.swing.JLabel jlKursIDLabela;
    private javax.swing.JLabel jlNastavnikGreska;
    private javax.swing.JLabel jlNazivUdzbenikaGreska;
    private javax.swing.JLabel jlNivoGreska;
    private javax.swing.JLabel jlStraniJezikGreska;
    private javax.swing.JLabel jlTermin1Greska;
    private javax.swing.JLabel jlTermin2Greska;
    private javax.swing.JPanel jpPodaciOKursu;
    private javax.swing.JSpinner jspnDatumPocetka;
    private javax.swing.JSpinner jspnDatumZavrsetka;
    private javax.swing.JSpinner jspnTermin1Cas;
    private javax.swing.JSpinner jspnTermin1Min;
    private javax.swing.JSpinner jspnTermin2Cas;
    private javax.swing.JSpinner jspnTermin2Min;
    private javax.swing.JTextField jtxtCenaKursa;
    private javax.swing.JTextField jtxtFondCasova;
    private javax.swing.JTextField jtxtNazivUdzbenika;
    // End of variables declaration//GEN-END:variables

    private void popuniCBStraniJezici() {
        try {
            List<StraniJezik> lista = Kontroler.vratiInstancu().dajStraneJezike();
            for (StraniJezik straniJezik : lista) {
                jcbStraniJezik.addItem(straniJezik);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju stranih jezika!");
        }
    }

    private void popuniCBNivo() {
        try {
            List<Nivo> lista = Kontroler.vratiInstancu().dajNivoe();
            for (Nivo nivo : lista) {
                jcbNivo.addItem(nivo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju nivoa!");
        }
    }

    private void popuniCBNastavnici() {
        try {
            List<Zaposleni> lista = Kontroler.vratiInstancu().dajZaposlene();
            for (Zaposleni nastavnik : lista) {
                jcbNastavnik.addItem(nastavnik);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju nastavnika!");
        }
    }

    public void noviKurs() {
        try {
            Kurs noviKurs = Kontroler.vratiInstancu().kreirajNoviKurs();
            jlKursID.setText(noviKurs.getKursID() + "");
            JOptionPane.showMessageDialog(this, "Sistem je kreirao novi kurs!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void srediFormu() {
        popuniCBStraniJezici();
        popuniCBNivo();
        popuniCBNastavnici();

        jbIzmeni.setVisible(false);
        jbObrisi.setVisible(false);
    }

    public void popuniPodatke(Kurs kurs) {
        jlKursID.setText(kurs.getKursID() + "");
        jcbStraniJezik.getModel().setSelectedItem(kurs.getJezik());
        jcbNivo.getModel().setSelectedItem(kurs.getNivo());
        jcbNastavnik.getModel().setSelectedItem(kurs.getNastavnik());
        jtxtFondCasova.setText(kurs.getFondCasova() + "");
        String[] d1 = kurs.getTermin1().split(" ");
        jcbTermin1Dan.getModel().setSelectedItem(d1[0]);
        String[] vreme1 = d1[1].split(":");
        jspnTermin1Cas.setValue(Integer.parseInt(vreme1[0]));
        jspnTermin1Min.setValue(Integer.parseInt(vreme1[1]));
        String[] d2 = kurs.getTermin2().split(" ");
        jcbTermin2Dan.getModel().setSelectedItem(d2[0]);
        String[] vreme2 = d2[1].split(":");
        jspnTermin2Cas.setValue(Integer.parseInt(vreme2[0]));
        jspnTermin2Min.setValue(Integer.parseInt(vreme2[1]));
        jspnDatumPocetka.setValue(kurs.getDatumOd());
        jspnDatumZavrsetka.setValue(kurs.getDatumDo());
        jtxtNazivUdzbenika.setText(kurs.getNazivUdzbenika());
        jtxtCenaKursa.setText(kurs.getCena() + "");
    }

    public void onemoguciUnos() {
        jlKursIDLabela.setVisible(true);
        jlKursID.setVisible(true);
        jbIzmeni.setVisible(true);
        jbObrisi.setVisible(true);

        jcbStraniJezik.setEnabled(false);
        jcbNivo.setEnabled(false);
        jcbNastavnik.setEnabled(false);
        jcbTermin1Dan.setEnabled(false);
        jcbTermin2Dan.setEnabled(false);

        jtxtFondCasova.setEditable(false);
        jspnTermin1Cas.setEnabled(false);
        jspnTermin1Min.setEnabled(false);
        jspnTermin2Cas.setEnabled(false);
        jspnTermin2Min.setEnabled(false);
        jtxtNazivUdzbenika.setEditable(false);
        jtxtCenaKursa.setEditable(false);

        jspnDatumPocetka.setEnabled(false);
        jspnDatumZavrsetka.setEnabled(false);

        jbSacuvaj.setEnabled(false);
        jbIzmeni.setEnabled(true);
        jbObrisi.setEnabled(true);
    }

    public void omoguciUnos() {
        jlKursIDLabela.setVisible(true);
        jlKursID.setVisible(true);
        jbIzmeni.setVisible(true);
        jbObrisi.setVisible(true);

        jcbStraniJezik.setEnabled(true);
        jcbNivo.setEnabled(true);
        jcbNastavnik.setEnabled(true);
        jcbTermin1Dan.setEnabled(true);
        jcbTermin2Dan.setEnabled(true);

        jtxtFondCasova.setEditable(true);
        jspnTermin1Cas.setEnabled(true);
        jspnTermin1Min.setEnabled(true);
        jspnTermin2Cas.setEnabled(true);
        jspnTermin2Min.setEnabled(true);
        jtxtNazivUdzbenika.setEditable(true);
        jtxtCenaKursa.setEditable(true);

        jspnDatumPocetka.setEnabled(true);
        jspnDatumZavrsetka.setEnabled(true);

        jbSacuvaj.setEnabled(true);
        jbIzmeni.setEnabled(false);
        jbObrisi.setEnabled(false);
    }
}
